Browser=Chrome
PracticeUrl=https://practicetestautomation.com/practice-test-login/
OrangeUrl=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
AltoroUrl=http://altoro.testfire.net/login.jsp
ChaseUrl=https://www.chase.com/